tickers:
- SPY
- QQQ
- IWM
- TLT
- AAPL
- MSFT
- NVDA
- AMD
- META
- TSLA
- KO
- PYPL

account_size: 42000.0
max_risk_per_trade_pct: 1.0
max_collateral_pct: 40.0
dte_min: 30
dte_max: 60
target_short_delta: 0.22
delta_band: 0.08
spread_width_low: 2.0
spread_width_high: 5.0
max_bid_ask_pct: 1.0
min_open_interest: 1
skip_earnings_within_days: 7
risk_free_rate: 0.045
take_profit_pct: 0.5
stop_loss_mult: 2.0
max_ideas: 3
provider: yfinance
polygon_api_key: null
tradier_access_token: null

